# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['run_server.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config.yaml', '.'),
        ('rebuild_all.bat', '.'),
        ('query_database/queries_config.yaml', 'query_database'),
        ('query_database/queries', 'query_database/queries'),
        ('query_database/object_catalog/queries', 'query_database/object_catalog/queries'),
        ('xml_fbograph/kuzu_build.txt', 'xml_fbograph'),
    ],
    hiddenimports=[
        'mcp', 'mcp.server', 'mcp.server.stdio', 'mcp.server.context',
        'mcp.server.lowlevel', 'mcp.server.lowlevel.server', 'mcp.types',
        'mcp.server.mcpserver', 'mcp.server.mcpserver.server', 'mcp.server.mcpserver.tools',
        'mcp.server.mcpserver.utilities.func_metadata',
        'pydantic', 'pydantic_core', 'anyio',
        'mcp_types',
        'yaml',
        'fastbusiness_mcp', 'fastbusiness_mcp.server', 'fastbusiness_mcp.mcp_app',
        'fastbusiness_mcp.stdio_safe', 'fastbusiness_mcp.tool_errors',
        'fastbusiness_mcp.utils.logger',
        'fastbusiness_mcp.config_paths',
        'find_connect_by_path',
        'find_connect_by_path.service',
        'find_connect_by_path.path_resolver',
        'find_connect_by_path.web_config_loader',
        'query_database',
        'query_database.service',
        'query_database.connection',
        'query_database.executor',
        'query_database.formatter',
        'query_database.query_resolver',
        'query_database.object_catalog.models',
        'query_database.object_catalog.fetcher',
        'query_database.bridges.summary_bridge',
        'query_database.bridges.summary_format',
        'antlr4',
        'tsql_engine',
        'tsql_engine.engine',
        'tsql_engine.preprocess',
        'tsql_engine.generated.TSqlLexer',
        'tsql_engine.generated.TSqlParser',
        'tsql_engine.generated.TSqlParserVisitor',
        'sql_object_summary',
        'sql_object_summary.models',
        'sql_object_summary.options',
        'sql_object_summary.classifier',
        'sql_object_summary.analyze',
        'sql_object_summary.snippet',
        'sql_object_summary.call_graph',
        'sql_object_summary.formatter',
        'sql_object_summary.visitors.summary_visitor',
        'sql_object_summary.visitors.param_effects',
        'find_entity_by_xml',
        'find_entity_by_xml.service',
        'find_entity_by_xml.entity_cache',
        'find_entity_by_xml.facade',
        'find_entity_by_xml.entity_expander',
        'find_entity_by_xml.formatter',
        'find_entity_by_xml.bridges.summary_xml_bridge',
        'find_entity_by_xml.bridges.summary_xml_format',
        'js_engine',
        'js_engine.engine',
        'js_engine.preprocess',
        'js_engine.errors',
        'js_engine.generated.JavaScriptLexer',
        'js_engine.generated.JavaScriptParser',
        'js_engine.generated.JavaScriptParserVisitor',
        'js_engine.generated.JavaScriptLexerBase',
        'js_engine.generated.JavaScriptParserBase',
        'xml_controller_summary',
        'xml_controller_summary.models',
        'xml_controller_summary.extract',
        'xml_controller_summary.field_classifier',
        'xml_controller_summary.analyze',
        'xml_controller_summary.formatter',
        'xml_controller_summary.fallback_regex',
        'xml_controller_summary.visitors.js_summary_visitor',
        'xml_controller_summary.visitors.sql_fragment_visitor',
        'lxml', 'lxml.etree',

        'clone_things',
        'clone_things.service',
        'clone_things.formatter',
        'clone_things.file_manager',
        'clone_things.open_editor',
        'clone_things.child_deps',
        'clone_things.db_ops',
        'clone_things.helpers',
        'clone_things.script_transform',
        'clone_things.type0_flow',
        'clone_things.type1_flow',
        'clone_things.type3_file_clone',
        'search_files',
        'search_files.service',
        'compare_things',
        'compare_things.service',
        'compare_things.formatter',
        'compare_things.file_compare',
        'compare_things.folder_compare',
        'compare_things.xml_compare',
        'compare_things.sql_compare',
        'compare_things.table_compare',
        'compare_things.models',
        'compare_things.meta_stat',
        'compare_things.line_diff',
        'compare_things.text_normalize',
        'compare_things.sql_fingerprint',
        'compare_things.sql_seed_scan',
        'compare_things.table_schema',
        'compare_things.db_access',
        'pyodbc',
        'search_qlyc',
        'search_qlyc.service',
        'search_qlyc.client',
        'search_qlyc.formatter',
        # FBOGraph + CLI rebuild Kuzu (fastbusiness_mcp.exe build ...)
        'kuzu',
        'xml_fbograph',
        'xml_fbograph.build_kuzu_projects',
        'xml_fbograph.builder.graph_builder',
        'xml_fbograph.storage.kuzu_index',
        'xml_fbograph.utils.path_helper',
        'xml_fbograph.parsers.xml_parser',
        'xml_fbograph.parsers.sql_parser',
        'xml_fbograph.parsers.js_parser',
        'xml_fbograph.mcp_tools',
        'xml_fbograph.query.engine',
        'xml_fbograph.service.watcher',
        'xml_fbograph.service.daemon',
        'xml_fbograph.rules.edges_rules',
        'xml_fbograph.core.schema',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy', 'pandas'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='fastbusiness_mcp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='fastbusiness_mcp',
)
