# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['run_server.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config.yaml', '.'),
        ('queryDatabase/queries_config.yaml', 'queryDatabase'),
        ('queryDatabase/queries', 'queryDatabase/queries'),
    ],
    hiddenimports=[
        'mcp', 'mcp.server', 'mcp.server.stdio', 'mcp.types',
        'yaml',
        'fastbusiness_mcp', 'fastbusiness_mcp.server',
        'fastbusiness_mcp.utils.logger',
        'fastbusiness_mcp.config_paths',
        'find_connect_by_path',
        'find_connect_by_path.service',
        'find_connect_by_path.path_resolver',
        'find_connect_by_path.web_config_loader',
        'queryDatabase',
        'queryDatabase.service',
        'queryDatabase.connection',
        'queryDatabase.executor',
        'queryDatabase.formatter',
        'queryDatabase.query_resolver',
        'find_entity_by_xml',
        'find_entity_by_xml.service',
        'find_entity_by_xml.entity_cache',
        'find_entity_by_xml.xml_entity_reader',
        'find_entity_by_xml.formatter',
        'lxml', 'lxml.etree',
        'pyodbc',
        # CodeGraph + CLI rebuild Kuzu (fastbusiness_mcp.exe build ...)
        'kuzu',
        'xml_codegraph',
        'xml_codegraph.build_kuzu_projects',
        'xml_codegraph.builder.graph_builder',
        'xml_codegraph.storage.kuzu_index',
        'xml_codegraph.utils.path_helper',
        'xml_codegraph.parsers.xml_parser',
        'xml_codegraph.parsers.sql_parser',
        'xml_codegraph.parsers.js_parser',
        'xml_codegraph.mcp_tools',
        'xml_codegraph.query.engine',
        'xml_codegraph.service.watcher',
        'xml_codegraph.service.daemon',
        'xml_codegraph.rules.edges_rules',
        'xml_codegraph.core.schema',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy', 'pandas'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='fastbusiness_mcp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='fastbusiness_mcp',
)
